### PR TITLE
feature/renaming to sc

### PR DESCRIPTION
**Pull request by ohheyitsdave**
renaming literals, mailto and url links to sensor.community

### CODE REVIEW

**Comment by ricki-z** [comment]
We should add something like '(formerly known as Luftdaten.info)' on the homepage. Some people may haven't registered the name change until now 😉 .

**Comment by ohheyitsdave** [comment]
> We should add something like '(formerly known as Luftdaten.info)' on the homepage. Some people may haven't registered the name change until now 😉 .

yes, good point. I'll add it on the first page.

**Comment by ohheyitsdave** [comment]
Added the additional information. Hope it's okay or do you have any other spot?

CleanShot 2020-11-27 at 15 59 36@2x

**Comment by ricki-z** [comment]
Passt. Und ist online.

**Pull request merged**
